"""empty message

Revision ID: 174b3ddd6a59
Revises: c02f4c62ba20
Create Date: 2022-01-12 23:02:00.275092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174b3ddd6a59'
down_revision = 'c02f4c62ba20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('prodcut_category_product_category_id_idx', table_name='product_category')
    op.drop_index('prodcut_category_product_definition_id_idx', table_name='product_category')
    op.drop_index('product_category_definition_name_idx', table_name='product_category_definition')
    op.drop_index('product_shop_product_definition_id_idx', table_name='product_shop')
    op.drop_index('product_shop_price_product_shop_id_idx', table_name='product_shop_price')
    op.drop_index('product_shop_price_scan_date_idx', table_name='product_shop_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_shop_price_scan_date_idx', 'product_shop_price', ['scan_date'], unique=False)
    op.create_index('product_shop_price_product_shop_id_idx', 'product_shop_price', ['product_shop_id'], unique=False)
    op.create_index('product_shop_product_definition_id_idx', 'product_shop', ['product_definition_id'], unique=False)
    op.create_index('product_category_definition_name_idx', 'product_category_definition', ['name'], unique=False)
    op.create_index('prodcut_category_product_definition_id_idx', 'product_category', ['product_definition_id'], unique=False)
    op.create_index('prodcut_category_product_category_id_idx', 'product_category', ['product_category_id'], unique=False)
    # ### end Alembic commands ###
