"""users table

Revision ID: 1cb3abd9b208
Revises: 499f53c08287
Create Date: 2019-11-19 00:21:07.051394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cb3abd9b208'
down_revision = '499f53c08287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ims_users', 'active',
               existing_type=sa.BOOLEAN(),
               comment='Is record is active',
               existing_nullable=False)
    op.alter_column('ims_users', 'created_by',
               existing_type=sa.INTEGER(),
               comment='Who created record',
               existing_nullable=False)
    op.alter_column('ims_users', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='PK record',
               existing_nullable=False)
    op.alter_column('ims_users', 'last_update_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp last update record',
               existing_nullable=True)
    op.alter_column('ims_users', 'update_last_by',
               existing_type=sa.INTEGER(),
               comment='Who last update record',
               existing_nullable=True)
    op.alter_column('ims_workers', 'active',
               existing_type=sa.BOOLEAN(),
               comment='Is record is active',
               existing_nullable=False)
    op.alter_column('ims_workers', 'created_by',
               existing_type=sa.INTEGER(),
               comment='Who created record',
               existing_nullable=False)
    op.alter_column('ims_workers', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='PK record',
               existing_nullable=False)
    op.alter_column('ims_workers', 'last_update_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp last update record',
               existing_nullable=True)
    op.alter_column('ims_workers', 'update_last_by',
               existing_type=sa.INTEGER(),
               comment='Who last update record',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ims_workers', 'update_last_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Who last update record',
               existing_nullable=True)
    op.alter_column('ims_workers', 'last_update_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp last update record',
               existing_nullable=True)
    op.alter_column('ims_workers', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='PK record',
               existing_nullable=False)
    op.alter_column('ims_workers', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Who created record',
               existing_nullable=False)
    op.alter_column('ims_workers', 'active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is record is active',
               existing_nullable=False)
    op.alter_column('ims_users', 'update_last_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Who last update record',
               existing_nullable=True)
    op.alter_column('ims_users', 'last_update_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp last update record',
               existing_nullable=True)
    op.alter_column('ims_users', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='PK record',
               existing_nullable=False)
    op.alter_column('ims_users', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Who created record',
               existing_nullable=False)
    op.alter_column('ims_users', 'active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is record is active',
               existing_nullable=False)
    # ### end Alembic commands ###
