"""Add uniq on ImageRepo.image

Revision ID: 1e2dc8bfb3c8
Revises: 6ab43ae15632
Create Date: 2020-10-26 21:24:37.182596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2dc8bfb3c8'
down_revision = '6ab43ae15632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_product_image', 'price_repo_image', ['image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_product_image', 'price_repo_image', type_='unique')
    # ### end Alembic commands ###
