"""add product table

Revision ID: 1fcfa0ff75a3
Revises: 73df723f9339
Create Date: 2020-09-28 16:36:48.491811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcfa0ff75a3'
down_revision = '73df723f9339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_product', sa.Column('category_id', sa.Integer(), nullable=False, comment='FK to category table'))
    op.add_column('price_product', sa.Column('slug', sa.Text(), nullable=False, comment='Slug of product for url, include category name'))
    op.alter_column('price_product', 'name',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='Name of product')
    op.create_foreign_key(None, 'price_product', 'price_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_product', type_='foreignkey')
    op.alter_column('price_product', 'name',
               existing_type=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='Name of product')
    op.drop_column('price_product', 'slug')
    op.drop_column('price_product', 'category_id')
    # ### end Alembic commands ###
