"""empty message

Revision ID: 2602c35764fd
Revises: 358ac87f3a2c
Create Date: 2021-11-21 11:30:06.203576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2602c35764fd'
down_revision = '358ac87f3a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_category1')
    op.drop_table('tmp_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_category',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('found_category', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tmp_category1',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('found_category', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
