"""empty message

Revision ID: 272972718366
Revises: f1fc9a9658ee
Create Date: 2021-11-25 01:26:52.046896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272972718366'
down_revision = 'f1fc9a9658ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tager_category_assignment_imp_catalog_page_id_key', 'tager_category_assignment', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tager_category_assignment_imp_catalog_page_id_key', 'tager_category_assignment', ['imp_catalog_page_id'])
    # ### end Alembic commands ###
