"""workers table

Revision ID: 2bf49b33896f
Revises: 8516e948e5e1
Create Date: 2019-11-19 17:18:17.712273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf49b33896f'
down_revision = '8516e948e5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ims_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False, comment='PK record'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='Who created record'),
    sa.Column('last_update_date', sa.DateTime(), nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.Integer(), nullable=True, comment='Who last update record'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Is record is deleted'),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthdays', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['ims_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ims_workers_arch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False, comment='PK record'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='Who created record'),
    sa.Column('last_update_date', sa.DateTime(), nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.Integer(), nullable=True, comment='Who last update record'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Is record is deleted'),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birthdays', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['ims_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ims_workers_arch')
    op.drop_table('ims_workers')
    # ### end Alembic commands ###
