"""empty message

Revision ID: 3269d85c8056
Revises: 61255a7c5cfa
Create Date: 2021-12-15 09:42:30.596421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3269d85c8056'
down_revision = '61255a7c5cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tager_brand_name_idx', 'tager_brand', ['name'], unique=False)
    op.create_index('tager_brand_assignment_brand_idx', 'tager_brand_assignment', ['brand'], unique=False)
    op.create_index('tager_brand_synonym_value_idx', 'tager_brand_synonym', ['value'], unique=False)
    op.create_index('tager_category_name_idx', 'tager_category', ['name'], unique=False)
    op.create_index('tager_category_synonym_value_idx', 'tager_category_synonym', ['value'], unique=False)
    op.create_index('tager_color_synonym_value_idx', 'tager_color_synonym', ['value'], unique=False)
    op.create_index('tager_tag_value_idx', 'tager_tag', ['value'], unique=False)
    op.create_index('tager_tag_synonym_value_idx', 'tager_tag_synonym', ['value'], unique=False)
    op.alter_column('tager_tagging_result', 'brand',
               existing_type=sa.TEXT(),
               comment='brands name',
               existing_comment='polish color name',
               existing_nullable=False)
    op.alter_column('tager_tagging_result', 'name',
               existing_type=sa.TEXT(),
               comment='product namee',
               existing_comment='polish color name',
               existing_nullable=False)
    op.alter_column('tager_tagging_result', 'orginal_title',
               existing_type=sa.TEXT(),
               comment='orginal title',
               existing_comment='polish color name',
               existing_nullable=False)
    op.create_index('tager_tagging_result_imp_catalog_page_id_idx', 'tager_tagging_result', ['imp_catalog_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tager_tagging_result_imp_catalog_page_id_idx', table_name='tager_tagging_result')
    op.alter_column('tager_tagging_result', 'orginal_title',
               existing_type=sa.TEXT(),
               comment='polish color name',
               existing_comment='orginal title',
               existing_nullable=False)
    op.alter_column('tager_tagging_result', 'name',
               existing_type=sa.TEXT(),
               comment='polish color name',
               existing_comment='product namee',
               existing_nullable=False)
    op.alter_column('tager_tagging_result', 'brand',
               existing_type=sa.TEXT(),
               comment='polish color name',
               existing_comment='brands name',
               existing_nullable=False)
    op.drop_index('tager_tag_synonym_value_idx', table_name='tager_tag_synonym')
    op.drop_index('tager_tag_value_idx', table_name='tager_tag')
    op.drop_index('tager_color_synonym_value_idx', table_name='tager_color_synonym')
    op.drop_index('tager_category_synonym_value_idx', table_name='tager_category_synonym')
    op.drop_index('tager_category_name_idx', table_name='tager_category')
    op.drop_index('tager_brand_synonym_value_idx', table_name='tager_brand_synonym')
    op.drop_index('tager_brand_assignment_brand_idx', table_name='tager_brand_assignment')
    op.drop_index('tager_brand_name_idx', table_name='tager_brand')
    # ### end Alembic commands ###
