"""empty message

Revision ID: 358ac87f3a2c
Revises: 476de45bd338
Create Date: 2021-11-15 23:14:35.347097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358ac87f3a2c'
down_revision = '476de45bd338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tager_brand', 'name',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Brands name')
    op.alter_column('tager_brand_synonym', 'value',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Brands synonym')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tager_brand_synonym', 'value',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Brands synonym')
    op.alter_column('tager_brand', 'name',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Brands name')
    # ### end Alembic commands ###
