"""empty message

Revision ID: 476de45bd338
Revises: 94845e6a6877
Create Date: 2021-11-14 12:23:12.658106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476de45bd338'
down_revision = '94845e6a6877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tager_brand_assignment', 'brand',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Brand Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tager_brand_assignment', 'brand',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Brand Name')
    # ### end Alembic commands ###
