"""users table

Revision ID: 499f53c08287
Revises: 76b0ddc53379
Create Date: 2019-11-19 00:18:15.220499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499f53c08287'
down_revision = '76b0ddc53379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ims_users', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment='Is record is deleted',
               existing_nullable=False)
    op.alter_column('ims_workers', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment='Is record is deleted',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ims_workers', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is record is deleted',
               existing_nullable=False)
    op.alter_column('ims_users', 'deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Is record is deleted',
               existing_nullable=False)
    # ### end Alembic commands ###
