"""empty message

Revision ID: 5f119aed69e8
Revises: 2602c35764fd
Create Date: 2021-11-21 23:17:39.715027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f119aed69e8'
down_revision = '2602c35764fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imp_catalog_page_status', sa.Column('specific_category__date', sa.Date(), nullable=True, comment='Tagged date'))
    op.drop_column('imp_catalog_page_status', 'tagged_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imp_catalog_page_status', sa.Column('tagged_date', sa.DATE(), autoincrement=False, nullable=True, comment='Tagged date'))
    op.drop_column('imp_catalog_page_status', 'specific_category__date')
    # ### end Alembic commands ###
