"""workers table

Revision ID: 6a05e818c4e4
Revises: 9d253c5d4af2
Create Date: 2019-11-19 17:33:29.279240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a05e818c4e4'
down_revision = '9d253c5d4af2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_workers', sa.Column('sex', sa.String(length=1), nullable=False))
    op.add_column('ims_workers_arch', sa.Column('sex', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_workers_arch', 'sex')
    op.drop_column('ims_workers', 'sex')
    # ### end Alembic commands ###
