"""Change fk in product_shop_url

Revision ID: 6ab43ae15632
Revises: 51a02da16eef
Create Date: 2020-10-26 21:17:01.468647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab43ae15632'
down_revision = '51a02da16eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_product_shop_url', 'shop_id',
               existing_type=sa.INTEGER(),
               comment='FK to shop repository',
               existing_comment='FK to images repository',
               existing_nullable=False)
    op.drop_constraint('price_product_shop_url_shop_id_fkey', 'price_product_shop_url', type_='foreignkey')
    op.create_foreign_key(None, 'price_product_shop_url', 'price_shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_product_shop_url', type_='foreignkey')
    op.create_foreign_key('price_product_shop_url_shop_id_fkey', 'price_product_shop_url', 'price_repo_image', ['shop_id'], ['id'])
    op.alter_column('price_product_shop_url', 'shop_id',
               existing_type=sa.INTEGER(),
               comment='FK to images repository',
               existing_comment='FK to shop repository',
               existing_nullable=False)
    # ### end Alembic commands ###
