"""empty message

Revision ID: 6e206811402e
Revises: 9a35b76ab9df
Create Date: 2021-12-02 22:24:29.424338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e206811402e'
down_revision = '9a35b76ab9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tager_tag_synonym_tager_tag_id_key', 'tager_tag_synonym', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tager_tag_synonym_tager_tag_id_key', 'tager_tag_synonym', ['tager_tag_id'])
    # ### end Alembic commands ###
