"""users table

Revision ID: 7010c33a150a
Revises: c694bfbb98a3
Create Date: 2019-11-19 00:01:31.666587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7010c33a150a'
down_revision = 'c694bfbb98a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_workers', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_workers', sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
