"""empty message

Revision ID: 744d656ab751
Revises: 0bab2dd20ad5
Create Date: 2021-07-02 15:30:32.526909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '744d656ab751'
down_revision = '0bab2dd20ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofert')
    op.add_column('price_tag', sa.Column('word', sa.Text(), nullable=True, comment='Orginal word'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_tag', 'word')
    op.create_table('ofert',
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='PK record'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False, comment='Who created record'),
    sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='Who last update record'),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is deleted'),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ofert_pkey')
    )
    # ### end Alembic commands ###
