"""users table

Revision ID: 76b0ddc53379
Revises: 2aaadb0835ff
Create Date: 2019-11-19 00:09:27.395858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b0ddc53379'
down_revision = '2aaadb0835ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('ims_users', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('ims_users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ims_users', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('ims_workers', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('ims_workers', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_workers', sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('ims_workers', 'active')
    op.drop_column('ims_users', 'description')
    op.drop_column('ims_users', 'deleted')
    op.drop_column('ims_users', 'avatar')
    op.drop_column('ims_users', 'active')
    # ### end Alembic commands ###
