"""users table

Revision ID: 8516e948e5e1
Revises: c8041371050b
Create Date: 2019-11-19 17:08:49.682464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8516e948e5e1'
down_revision = 'c8041371050b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ims_users_arch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False, comment='PK record'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='Who created record'),
    sa.Column('last_update_date', sa.DateTime(), nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.Integer(), nullable=True, comment='Who last update record'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='Is record is deleted'),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ims_users_arch_email'), 'ims_users_arch', ['email'], unique=True)
    op.create_index(op.f('ix_ims_users_arch_name'), 'ims_users_arch', ['name'], unique=True)
    op.drop_table('ims_workers')
    op.drop_column('ims_users', 'description')
    op.drop_column('ims_users', 'parmas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users', sa.Column('parmas', sa.TEXT(), autoincrement=False, nullable=True, comment='Additional space for data storage for the record'))
    op.add_column('ims_users', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('ims_workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='PK record'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False, comment='Who created record'),
    sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='Who last update record'),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birthdays', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is deleted'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is active'),
    sa.Column('parmas', sa.TEXT(), autoincrement=False, nullable=True, comment='Additional space for data storage for the record'),
    sa.ForeignKeyConstraint(['user_id'], ['ims_users.id'], name='ims_workers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ims_workers_pkey')
    )
    op.drop_index(op.f('ix_ims_users_arch_name'), table_name='ims_users_arch')
    op.drop_index(op.f('ix_ims_users_arch_email'), table_name='ims_users_arch')
    op.drop_table('ims_users_arch')
    # ### end Alembic commands ###
