"""empty message

Revision ID: 9409af8e7a50
Revises: 81c0fba38162
Create Date: 2021-10-13 11:12:22.953795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9409af8e7a50'
down_revision = '81c0fba38162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imp_product_page', sa.Column('category', sa.Text(), nullable=True, comment='Product category'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imp_product_page', 'category')
    # ### end Alembic commands ###
