"""empty message

Revision ID: 95e86ce2269d
Revises: 272972718366
Create Date: 2021-11-29 23:19:28.446471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e86ce2269d'
down_revision = '272972718366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tager_color_synonym', sa.Column('tager_color_id', sa.Integer(), nullable=False, comment='FK to tager_color.id table'))
    op.drop_constraint('tager_color_synonym_tager_brand_id_fkey', 'tager_color_synonym', type_='foreignkey')
    op.create_foreign_key(None, 'tager_color_synonym', 'tager_color', ['tager_color_id'], ['id'])
    op.drop_column('tager_color_synonym', 'tager_brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tager_color_synonym', sa.Column('tager_brand_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to tager_color.id table'))
    op.drop_constraint(None, 'tager_color_synonym', type_='foreignkey')
    op.create_foreign_key('tager_color_synonym_tager_brand_id_fkey', 'tager_color_synonym', 'tager_color', ['tager_brand_id'], ['id'])
    op.drop_column('tager_color_synonym', 'tager_color_id')
    # ### end Alembic commands ###
