"""empty message

Revision ID: 9b5261eeb5e6
Revises: 174b3ddd6a59
Create Date: 2022-01-18 11:58:34.292258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5261eeb5e6'
down_revision = '174b3ddd6a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_category_definition_meta_category_id_idx', 'product_category_definition', ['meta_category_id'], unique=False)
    op.create_index('product_img_img_source_idx', 'product_img', ['img_source'], unique=False)
    op.create_index('product_img_orginal_images_ididx', 'product_img', ['orginal_images_id'], unique=False)
    op.create_index('product_shop_imp_catalog_page_id_idx', 'product_shop', ['imp_catalog_page_id'], unique=False)
    op.create_index('product_shop_shop_id_idx', 'product_shop', ['shop_id'], unique=False)
    op.create_index('product_shop_price_scan_date_idx', 'product_shop_price', ['scan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_shop_price_scan_date_idx', table_name='product_shop_price')
    op.drop_index('product_shop_shop_id_idx', table_name='product_shop')
    op.drop_index('product_shop_imp_catalog_page_id_idx', table_name='product_shop')
    op.drop_index('product_img_orginal_images_ididx', table_name='product_img')
    op.drop_index('product_img_img_source_idx', table_name='product_img')
    op.drop_index('product_category_definition_meta_category_id_idx', table_name='product_category_definition')
    # ### end Alembic commands ###
