"""workers table

Revision ID: 9d253c5d4af2
Revises: d61f3b00f2b4
Create Date: 2019-11-19 17:31:53.348450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d253c5d4af2'
down_revision = 'd61f3b00f2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users', sa.Column('passwd', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_ims_users_passwd'), 'ims_users', ['passwd'], unique=False)
    op.drop_index('ix_ims_users_password', table_name='ims_users')
    op.drop_column('ims_users', 'password')
    op.add_column('ims_users_arch', sa.Column('passwd', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_ims_users_arch_passwd'), 'ims_users_arch', ['passwd'], unique=False)
    op.drop_index('ix_ims_users_arch_password', table_name='ims_users_arch')
    op.drop_column('ims_users_arch', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users_arch', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_ims_users_arch_password', 'ims_users_arch', ['password'], unique=False)
    op.drop_index(op.f('ix_ims_users_arch_passwd'), table_name='ims_users_arch')
    op.drop_column('ims_users_arch', 'passwd')
    op.add_column('ims_users', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_ims_users_password', 'ims_users', ['password'], unique=False)
    op.drop_index(op.f('ix_ims_users_passwd'), table_name='ims_users')
    op.drop_column('ims_users', 'passwd')
    # ### end Alembic commands ###
