"""remove uniq from tag's table

Revision ID: a57b9d70b684
Revises: be4a5cf48535
Create Date: 2020-11-10 17:02:49.472108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57b9d70b684'
down_revision = 'be4a5cf48535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('price_tag_meaning_key', 'price_tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('price_tag_meaning_key', 'price_tag', ['meaning'])
    # ### end Alembic commands ###
