"""empty message

Revision ID: aeaba3dcbae5
Revises: 2b8fe115f3be
Create Date: 2021-11-14 12:05:10.121775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaba3dcbae5'
down_revision = '2b8fe115f3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tager_brand_assignment', sa.Column('brand', sa.Text(), nullable=True, comment='Brand Name'))
    op.add_column('Tager_brand_assignment', sa.Column('imp_catalog_page_id', sa.Integer(), nullable=False, comment='FK to imp_catalog_page.id table'))
    op.create_unique_constraint(None, 'Tager_brand_assignment', ['imp_catalog_page_id'])
    op.create_foreign_key(None, 'Tager_brand_assignment', 'imp_catalog_page', ['imp_catalog_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tager_brand_assignment', type_='foreignkey')
    op.drop_constraint(None, 'Tager_brand_assignment', type_='unique')
    op.drop_column('Tager_brand_assignment', 'imp_catalog_page_id')
    op.drop_column('Tager_brand_assignment', 'brand')
    # ### end Alembic commands ###
