"""add color

Revision ID: be4a5cf48535
Revises: c66665cbe677
Create Date: 2020-11-10 17:00:36.206873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4a5cf48535'
down_revision = 'c66665cbe677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_tag_id_value', table_name='price_tag')
    op.drop_index('uniq_price_tag_value', table_name='price_tag')
    op.create_unique_constraint(None, 'price_tag', ['meaning'])
    op.drop_index('idx_price_tag_product_multi', table_name='price_tag_product')
    op.drop_index('idx_price_tag_product_tag_id', table_name='price_tag_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_price_tag_product_tag_id', 'price_tag_product', ['tag_id'], unique=False)
    op.create_index('idx_price_tag_product_multi', 'price_tag_product', ['tag_id', 'tag_product_def_id', 'active', 'deleted'], unique=False)
    op.drop_constraint(None, 'price_tag', type_='unique')
    op.create_index('uniq_price_tag_value', 'price_tag', ['value'], unique=True)
    op.create_index('idx_price_tag_id_value', 'price_tag', ['id', 'value'], unique=False)
    # ### end Alembic commands ###
