"""empty message

Revision ID: c02f4c62ba20
Revises: 3269d85c8056
Create Date: 2022-01-07 16:14:22.605653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02f4c62ba20'
down_revision = '3269d85c8056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_img', sa.Column('path_big', sa.Text(), nullable=True, comment='Path to image'))
    op.add_column('product_img', sa.Column('path_thumbs', sa.Text(), nullable=False, comment='Path to image'))
    op.drop_column('product_img', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_img', sa.Column('path', sa.TEXT(), autoincrement=False, nullable=False, comment='Path to image'))
    op.drop_column('product_img', 'path_thumbs')
    op.drop_column('product_img', 'path_big')
    # ### end Alembic commands ###
