"""empty message

Revision ID: c08c7f20ea9b
Revises: 376e739c17ee
Create Date: 2022-02-10 14:24:01.332290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08c7f20ea9b'
down_revision = '376e739c17ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_shop_price_product_shop_id_idx', 'product_shop_price', ['product_shop_id'], unique=False)
    op.drop_index('product_shop_price_scan_date_idx', table_name='product_shop_price')
    op.create_index('product_shop_price_scan_date_idx', 'product_shop_price', ['scan_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_shop_price_scan_date_idx', table_name='product_shop_price')
    op.create_index('product_shop_price_scan_date_idx', 'product_shop_price', ['product_shop_id'], unique=False)
    op.drop_index('product_shop_price_product_shop_id_idx', table_name='product_shop_price')
    # ### end Alembic commands ###
