"""New tables

Revision ID: c517a848cf3d
Revises: 
Create Date: 2020-09-20 21:10:48.387541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c517a848cf3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='PK record'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False, comment='Who created record'),
    sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp last update record'),
    sa.Column('update_last_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='Who last update record'),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is deleted'),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('control_sum', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dimension', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('orientation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('main_color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    # ### end Alembic commands ###
