"""change tags structure

Revision ID: c66665cbe677
Revises: 1efc80c38833
Create Date: 2020-11-02 21:46:20.359642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c66665cbe677'
down_revision = '1efc80c38833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_tags_products')
    op.add_column('price_tag_ofert', sa.Column('tag_product_def_id', sa.Integer(), nullable=False, comment='FK to price_tag_product_def table'))
    op.drop_constraint('price_tag_ofert_tag_product_id_fkey', 'price_tag_ofert', type_='foreignkey')
    op.create_foreign_key(None, 'price_tag_ofert', 'price_tag_product_def', ['tag_product_def_id'], ['id'])
    op.drop_column('price_tag_ofert', 'tag_product_id')
    op.add_column('price_tag_product', sa.Column('tag_product_def_id', sa.Integer(), nullable=False, comment='FK to price_tag_product_def table'))
    op.create_foreign_key(None, 'price_tag_product', 'price_tag_product_def', ['tag_product_def_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_tag_product', type_='foreignkey')
    op.drop_column('price_tag_product', 'tag_product_def_id')
    op.add_column('price_tag_ofert', sa.Column('tag_product_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to tag table'))
    op.drop_constraint(None, 'price_tag_ofert', type_='foreignkey')
    op.create_foreign_key('price_tag_ofert_tag_product_id_fkey', 'price_tag_ofert', 'price_tag_ofert', ['tag_product_id'], ['id'])
    op.drop_column('price_tag_ofert', 'tag_product_def_id')
    op.create_table('price_tags_products',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to tag table'),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is deleted'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False, comment='Who created record'),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp created record'),
    sa.Column('last_update_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='Who last update record'),
    sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp last update record'),
    sa.ForeignKeyConstraint(['tag_id'], ['price_tag.id'], name='price_tags_products_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='price_tags_products_pkey')
    )
    # ### end Alembic commands ###
