"""users table

Revision ID: c694bfbb98a3
Revises: f15a379af750
Create Date: 2019-11-18 23:57:27.815904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c694bfbb98a3'
down_revision = 'f15a379af750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_workers', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('ims_workers', sa.Column('birthdays', sa.Date(), nullable=True))
    op.add_column('ims_workers', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ims_workers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('ims_workers', sa.Column('user_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_workers', 'user_name')
    op.drop_column('ims_workers', 'description')
    op.drop_column('ims_workers', 'deleted')
    op.drop_column('ims_workers', 'birthdays')
    op.drop_column('ims_workers', 'avatar')
    # ### end Alembic commands ###
