"""users table

Revision ID: c8041371050b
Revises: 1cb3abd9b208
Create Date: 2019-11-19 00:30:43.549128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8041371050b'
down_revision = '1cb3abd9b208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users', sa.Column('parmas',  sa.Text(), nullable=True, comment='Additional space for data storage for the record'))
    op.add_column('ims_workers', sa.Column('parmas',  sa.Text(), nullable=True, comment='Additional space for data storage for the record'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ims_workers', 'parmas')
    op.drop_column('ims_users', 'parmas')
    # ### end Alembic commands ###
