"""workers table

Revision ID: d61f3b00f2b4
Revises: 2bf49b33896f
Create Date: 2019-11-19 17:30:16.799447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61f3b00f2b4'
down_revision = '2bf49b33896f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users', sa.Column('next_pas_change', sa.Date(), nullable=False))
    op.add_column('ims_users', sa.Column('pas_change_req', sa.Boolean(), nullable=False))
    op.add_column('ims_users', sa.Column('password', sa.String(length=120), nullable=True))
    op.add_column('ims_users', sa.Column('salt', sa.String(length=64), nullable=True))
    op.add_column('ims_users', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.add_column('ims_users', sa.Column('user_type', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ims_users_password'), 'ims_users', ['password'], unique=False)
    op.create_index(op.f('ix_ims_users_salt'), 'ims_users', ['salt'], unique=False)
    op.create_index(op.f('ix_ims_users_user_name'), 'ims_users', ['user_name'], unique=True)
    op.create_index(op.f('ix_ims_users_user_type'), 'ims_users', ['user_type'], unique=False)
    op.drop_index('ix_ims_users_name', table_name='ims_users')
    op.drop_column('ims_users', 'name')
    op.add_column('ims_users_arch', sa.Column('next_pas_change', sa.Date(), nullable=False))
    op.add_column('ims_users_arch', sa.Column('pas_change_req', sa.Boolean(), nullable=False))
    op.add_column('ims_users_arch', sa.Column('password', sa.String(length=120), nullable=True))
    op.add_column('ims_users_arch', sa.Column('salt', sa.String(length=64), nullable=True))
    op.add_column('ims_users_arch', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.add_column('ims_users_arch', sa.Column('user_type', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ims_users_arch_password'), 'ims_users_arch', ['password'], unique=False)
    op.create_index(op.f('ix_ims_users_arch_salt'), 'ims_users_arch', ['salt'], unique=False)
    op.create_index(op.f('ix_ims_users_arch_user_name'), 'ims_users_arch', ['user_name'], unique=True)
    op.create_index(op.f('ix_ims_users_arch_user_type'), 'ims_users_arch', ['user_type'], unique=False)
    op.drop_index('ix_ims_users_arch_name', table_name='ims_users_arch')
    op.drop_column('ims_users_arch', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ims_users_arch', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_ims_users_arch_name', 'ims_users_arch', ['name'], unique=True)
    op.drop_index(op.f('ix_ims_users_arch_user_type'), table_name='ims_users_arch')
    op.drop_index(op.f('ix_ims_users_arch_user_name'), table_name='ims_users_arch')
    op.drop_index(op.f('ix_ims_users_arch_salt'), table_name='ims_users_arch')
    op.drop_index(op.f('ix_ims_users_arch_password'), table_name='ims_users_arch')
    op.drop_column('ims_users_arch', 'user_type')
    op.drop_column('ims_users_arch', 'user_name')
    op.drop_column('ims_users_arch', 'salt')
    op.drop_column('ims_users_arch', 'password')
    op.drop_column('ims_users_arch', 'pas_change_req')
    op.drop_column('ims_users_arch', 'next_pas_change')
    op.add_column('ims_users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_ims_users_name', 'ims_users', ['name'], unique=True)
    op.drop_index(op.f('ix_ims_users_user_type'), table_name='ims_users')
    op.drop_index(op.f('ix_ims_users_user_name'), table_name='ims_users')
    op.drop_index(op.f('ix_ims_users_salt'), table_name='ims_users')
    op.drop_index(op.f('ix_ims_users_password'), table_name='ims_users')
    op.drop_column('ims_users', 'user_type')
    op.drop_column('ims_users', 'user_name')
    op.drop_column('ims_users', 'salt')
    op.drop_column('ims_users', 'password')
    op.drop_column('ims_users', 'pas_change_req')
    op.drop_column('ims_users', 'next_pas_change')
    # ### end Alembic commands ###
