"""empty message

Revision ID: dc0380d73295
Revises: 6e206811402e
Create Date: 2021-12-02 22:32:09.147757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0380d73295'
down_revision = '6e206811402e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tager_tag_tager_context_id_key', 'tager_tag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tager_tag_tager_context_id_key', 'tager_tag', ['tager_context_id'])
    # ### end Alembic commands ###
