"""users table

Revision ID: f15a379af750
Revises: 4720f04c8d97
Create Date: 2019-11-17 23:39:32.669510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15a379af750'
down_revision = '4720f04c8d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ims_users_email'), 'ims_users', ['email'], unique=True)
    op.create_index(op.f('ix_ims_users_name'), 'ims_users', ['name'], unique=True)
    op.drop_constraint('ims_users_email_key', 'ims_users', type_='unique')
    op.drop_constraint('ims_users_name_key', 'ims_users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ims_users_name_key', 'ims_users', ['name'])
    op.create_unique_constraint('ims_users_email_key', 'ims_users', ['email'])
    op.drop_index(op.f('ix_ims_users_name'), table_name='ims_users')
    op.drop_index(op.f('ix_ims_users_email'), table_name='ims_users')
    # ### end Alembic commands ###
