"""empty message

Revision ID: f1fc9a9658ee
Revises: 5649c3b1f211
Create Date: 2021-11-23 15:41:43.986224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fc9a9658ee'
down_revision = '5649c3b1f211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tager_category_synonym', sa.Column('tager_category_id', sa.Integer(), nullable=False, comment='FK to tager_category.id table'))
    op.drop_constraint('tager_category_synonym_def_category_id_fkey', 'tager_category_synonym', type_='foreignkey')
    op.create_foreign_key(None, 'tager_category_synonym', 'tager_category', ['tager_category_id'], ['id'])
    op.drop_column('tager_category_synonym', 'def_category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tager_category_synonym', sa.Column('def_category_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to tager_category.id table'))
    op.drop_constraint(None, 'tager_category_synonym', type_='foreignkey')
    op.create_foreign_key('tager_category_synonym_def_category_id_fkey', 'tager_category_synonym', 'tager_category', ['def_category_id'], ['id'])
    op.drop_column('tager_category_synonym', 'tager_category_id')
    # ### end Alembic commands ###
