"""add slug to category

Revision ID: f7f0fa47710a
Revises: 9a76ddfb3fa0
Create Date: 2020-10-14 19:21:56.129575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f0fa47710a'
down_revision = '9a76ddfb3fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_category', sa.Column('slug', sa.Text(), nullable=True, comment='Slug of category for url'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_category', 'slug')
    # ### end Alembic commands ###
