"""empty message

Revision ID: fd82f8fb41f1
Revises: 744d656ab751
Create Date: 2021-10-09 13:09:58.653962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd82f8fb41f1'
down_revision = '744d656ab751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imp_catalog_page')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imp_catalog_page',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_point_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='FK to entry_point_id table'),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False, comment='url to product'),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False, comment='Product title form catalog page'),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=True, comment='url to main image'),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True, comment='Brand Name'),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is active'),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is record is deleted'),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False, comment='Who created record'),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Timestamp created record'),
    sa.Column('last_update_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='Who last update record'),
    sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Timestamp last update record'),
    sa.ForeignKeyConstraint(['entry_point_id'], ['price_entry_point.id'], name='imp_catalog_page_entry_point_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='imp_catalog_page_pkey')
    )
    # ### end Alembic commands ###
